### ISSUE TITLE
Bug with flows

### ISSUE THREAD

**Issue by ilpepe** [genohm/slims-python-api#3]
Hi,
I wrote python code to get to add flow.

`def addFlowGenerateGrowthTemplate():
	"""
	# INTRO
	Add flow to SLims.
    # INPUT

	# OUTPUT
	"""
	slims = test_slims_flow() #code tot start the connection
	slims.add_flow(
		flow_id="GrowthExperiment",
		name="GrowthExperiment",
		usage="CONTENT_MANAGEMENT",
		steps=[
			Step(
				name="Select Growth Experiments",
				action=parseSelection,
				input=[
					{'name': "SLIMS_SELECT_SAMPLES", 'label': "SLIMS_SELECT_SAMPLES", 'type': "STRINGARRAY"}
				]
			)
		]
	)

def parseSelection(flow_run):
	"""
	# INTRO

	# INPUT

	# OUTPUT
	"""
	pks = flow_run.data["SLIMS_SELECT_SAMPLES"]

	data_tuple = tuple2Experiment(pks)

	write2Template(data_tuple, app_config.path_template)
`

Sometimes this works, sometimes it doesn't. Error code:

`[2017-08-07 11:03:51,843] ERROR in app: Exception on /slims/GrowthExperiment/0 [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/slims/slims.py", line 31, in _start_step
    return_value = slims_instances[name]._execute_operation(operation, step, data)
  File "/usr/local/lib/python3.5/dist-packages/slims/slims.py", line 297, in _execute_operation
    output = self.operations[operation + "/" + str(step)].execute(flow_run)
KeyError: 'GrowthExperiment/0'
`

Which seems to be a bug in the SLims python api code.
So I get a successful registration of the flow, I see the button in SLims, I'm able to push the button.

any help before I dive in the source code it self?
Best regards,
Pieter

**Comment by gastonsken** [comment]
Hi Pieter,

I was not able to reproduce this problem with the supplied code.
Could you provide us the complete code in a pm?
You say that the code sometimes works and sometimes doesn't. Could you elaborate on that? Does it fails and succeeds in a single run of the python script or does it either fails or succeeds on startup of the script?

Kind regards,
Dries
